# Generated by Django 6.1 on 2026-10-08 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('level', models.CharField(max_length=80)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('location', models.CharField(max_length=100)),
                ('intakes', models.JSONField(default=list)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('city', models.CharField(max_length=80)),
                ('venue', models.CharField(max_length=160)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('capacity', models.PositiveIntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('intake', models.CharField(max_length=40)),
                ('destination', models.CharField(max_length=100)),
                ('student_location', models.CharField(max_length=120)),
                ('message', models.TextField(blank=True)),
                ('reference', models.CharField(max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portal.course')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portal.event')),
            ],
            options={
                'indexes': [models.Index(fields=['email', 'course', 'event'], name='portal_inqu_email_39b296_idx'), models.Index(fields=['full_name'], name='portal_inqu_full_na_a4cb0e_idx'), models.Index(fields=['reference'], name='portal_inqu_referen_6c3a47_idx')],
            },
        ),
    ]
