# Generated by Django 5.2.18 on 2026-10-08 22:37

import django.db.models.deletion
from django.db import migrations, models


UNIVERSITIES = {
    'University of Cape Town': ('South Africa', 'Cape Town', 'https://images.unsplash.com/photo-1564981797816-1043664bf78d?auto=format&fit=crop&w=480&q=80'),
    'National University of Singapore': ('Singapore', 'Singapore', 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?auto=format&fit=crop&w=480&q=80'),
    'University of Manchester': ('United Kingdom', 'Manchester', 'https://images.unsplash.com/photo-1498243691581-b145c3f54a5a?auto=format&fit=crop&w=480&q=80'),
    'University of Toronto': ('Canada', 'Toronto', 'https://images.unsplash.com/photo-1541339907198-e08756?auto=format&fit=crop&w=480&q=80'),
    'University of Melbourne': ('Australia', 'Melbourne', 'https://images.unsplash.com/photo-1606761568499-6d2451b23c66?auto=format&fit=crop&w=480&q=80'),
}


def seed_universities(apps, schema_editor):
    University = apps.get_model('portal', 'University')
    CourseOffering = apps.get_model('portal', 'CourseOffering')
    for name, (country, city, image_url) in UNIVERSITIES.items():
        university, _ = University.objects.get_or_create(name=name, defaults={
            'country': country, 'city': city, 'image_url': image_url,
        })
        for offering in CourseOffering.objects.filter(institution=name):
            offering.university = university
            offering.price = offering.course.price
            offering.save(update_fields=['university', 'price'])


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_course_offerings'),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, unique=True)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='courseoffering',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='course_offering',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inquiries', to='portal.courseoffering'),
        ),
        migrations.AddField(
            model_name='courseoffering',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='course_offerings', to='portal.university'),
        ),
        migrations.RunPython(seed_universities, migrations.RunPython.noop),
    ]
