# Generated by Django 5.2.18 on 2026-10-08 22:57

from django.db import migrations, models


OPTIONS = {
    'programme_type': ['Undergraduate', 'Postgraduate', 'PhD', 'Certificate', 'Diploma'],
    'destination': ['United Kingdom', 'United States', 'Canada', 'Australia', 'Ireland', 'Germany', 'France', 'Netherlands'],
    'region': ['Africa', 'Asia', 'Europe', 'North America', 'Oceania'],
}


def seed_options(apps, schema_editor):
    PortalOption = apps.get_model('portal', 'PortalOption')
    for option_type, values in OPTIONS.items():
        for order, value in enumerate(values):
            PortalOption.objects.get_or_create(option_type=option_type, value=value, defaults={'sort_order': order})


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_refresh_university_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_type', models.CharField(choices=[('programme_type', 'Programme type'), ('destination', 'Destination'), ('region', 'Study region')], max_length=40)),
                ('value', models.CharField(max_length=120)),
                ('active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['option_type', 'sort_order', 'value'],
                'constraints': [models.UniqueConstraint(fields=('option_type', 'value'), name='portal_option_unique')],
            },
        ),
        migrations.RunPython(seed_options, migrations.RunPython.noop),
    ]
