# Generated by Django 5.2.18 on 2026-10-10 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0012_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='portalaccesscode',
            name='code_encrypted',
            field=models.TextField(blank=True, default=''),
        ),
    ]
